bind_addr = ":8083"
log_level = "debug"

[store]
database_url = "postgres://postgres:password@localhost/restapi_dev?sslmode=disable"
test_database_url = "postgres://postgres:password@localhost/restapi_test?sslmode=disable"
